nama = input("Masukkan Nama:")
nim = input("Masukkan NIM:")
paralel = input("Masukkan Kelas Paralel:")
ttl = input("Masukkan Tempat/Tanggal Lahir (dipisah dengan koma):")
alamat = input("Masukkan Alamat:")
hobby = input("Masukkan Hobby:")
hp = input("Masukkan No.HP:")
print(f"Nama                :{nama}")
print(f"NIM                 :{nim}")
print(f"Kelas Paralel       :{paralel}")
print(f"Tempat/Tanggal Lahir:{ttl}")
print(f"Alamat              :{alamat}")
print(f"Hobby               :{hobby}")
print(f"No.HP               :{hp}")